one = int(input("Insert first number "))
two = int(input("Insert second number "))
three = int(input("Insert third number "))
print("\/Anssver will be bellow this text\/")
print(one + two + three)